### ISSUE TITLE
please share how to build dist folder & help with error

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [indraraj26/ion-camera#3]
Hi  Indraraj you did wonderful job : )  
can you please share build script so i can customise this plugin and add more functionality.

```
"scripts": {
    "build": "rm -rf dist && npm run build.ng"
  }
```

also getting error after import into ionic blank project

```
ERROR Error: Uncaught (in promise): Error: inject() must be called from an injection context
Error: inject() must be called from an injection context
```

**Comment by indraraj26** [comment]
Hi @bhandaribhuminpfizer ,

These are the commands to build the projects [build script](https://github.com/indraraj26/ion-camera/blob/master/package.json)

You can do changes in projects/ion-camera after that just run the `npm run lib` then `ionic cordova build android` to test in real device.


Let me know if you have any questions.

Edit:

Just tested and working fine for me. could you please create minimal repo to reproduce.

repo: https://github.com/indraraj26/test-ion-camera

Thank you.

**Comment by bhandaribhuminpfizer** [comment]
Hey @indraraj26 not asking about project i am asking about @indraraj26/ion-camera  package build, i did not see any script for build package
Like: 
"scripts": {
    "build": "ng-packagr -p ng-package.json"
  },

**Comment by indraraj26** [comment]
Please see the tutorial 
1. https://medium.com/@tomsu/how-to-build-a-library-for-angular-apps-4f9b38b0ed11
2. https://jinalshah999.medium.com/how-to-build-and-publish-angular-library-a333d6ff12c0

For general question how to build angular library please ask in https://stackoverflow.com/

Closing this thread it is working as expected.
